name: looper_player
description: "Looper Player - A powerful music player."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.7.0+30

environment:
  sdk: ^3.11.0


dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.9
  lucide_icons_flutter: ^3.1.19
  animations: ^3.0.0
  window_manager: ^0.5.2
  google_fonts: ^8.2.1
  squiggly_slider: ^2.0.0
  adaptive_palette: ^3.1.0
  material_color_utilities: any

  # State Management
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # Audio Playback
  mpv_audio_kit: ^0.4.5

  # Database
  isar_community: ^3.3.2
  isar_community_flutter_libs: ^3.3.2

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.3
  
  # SVG Support
  flutter_svg: ^2.3.0
  lottie: ^3.3.0

  # Utilities
  url_launcher: ^6.3.2
  path_provider: ^2.1.6
  path: ^1.9.1
  permission_handler: ^11.3.1
  file_picker: ^12.3.0
  http: ^1.6.0
  cached_network_image: ^3.4.1
  share_plus: ^13.3.0
  marqueer: ^2.5.0
  wakelock_plus: ^1.8.0
  flutter_hsvcolor_picker: ^1.5.1
  flutter_displaymode: ^0.7.0
  package_info_plus: ^10.2.1
  home_widget: ^0.9.4
  metadata_god: ^1.1.0
  appambit_sdk_flutter: ^1.2.0
  gal: ^2.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^4.0.3
  isar_community_generator: ^3.3.2
  flutter_distributor: ^0.6.6
  flutter_launcher_icons: ^0.14.4
  coverage: ^1.15.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/launcher_logo.png"
  adaptive_icon_background: "#242424" #55DF69"
  adaptive_icon_foreground: "assets/launcher_logo_adaptive.png"
  adaptive_icon_foreground_inset: 0
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/music_bar_Icons/
    - assets/side_bar/
    - assets/about/
    - assets/android_icons/
    - assets/android_icons/avatars/
  shaders:
    - media/shaders/ambient_noise.frag
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost/static/Jost-Thin.ttf
          weight: 100
        - asset: assets/fonts/Jost/static/Jost-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Jost/static/Jost-Light.ttf
          weight: 300
        - asset: assets/fonts/Jost/static/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jost/static/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost/static/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Jost/static/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jost/static/Jost-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Jost/static/Jost-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
    - family: Space Grotesk
      fonts:
        - asset: assets/fonts/Space_Grotesk/static/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/Space_Grotesk/static/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/Space_Grotesk/static/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/Space_Grotesk/static/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Space_Grotesk/static/SpaceGrotesk-Bold.ttf
          weight: 700
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DM_Sans/static/DMSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/DM_Sans/static/DMSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/DM_Sans/static/DMSans-Light.ttf
          weight: 300
        - asset: assets/fonts/DM_Sans/static/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DM_Sans/static/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DM_Sans/static/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DM_Sans/static/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DM_Sans/static/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/DM_Sans/static/DMSans-Black.ttf
          weight: 900
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-ExtraBold.ttf
          weight: 800
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora/static/Sora-Thin.ttf
          weight: 100
        - asset: assets/fonts/Sora/static/Sora-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Sora/static/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora/static/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sora/static/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora/static/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora/static/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora/static/Sora-ExtraBold.ttf
          weight: 800
    - family: Google Sans
      fonts:
        - asset: assets/fonts/Google_Sans/static/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Google_Sans/static/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Google_Sans/static/GoogleSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Google_Sans/static/GoogleSans-Bold.ttf
          weight: 700

