app_name: Looper Player
package_name: looper-player
executable_name: looper_player
display_name: Looper Player
generic_name: Music Player
version: 1.0.0
architecture: amd64
maintainer:
  name: nilshaaa
  email: nilshaaa@example.com
installed_size: 25000
description: A modern, high-fidelity music player for Linux.
section: utils
priority: optional
icon: assets/logo_linux.png
categories:
  - AudioVideo
  - Audio
  - Music
  - Player
depends:
  - libgtk-3-0
  - libvlc5
  - libmpv2
