name: one-player
base: core22
version: '1.0.0'
summary: A modern music player built with Flutter
description: |
  A native, production-ready Linux music player built with Flutter.
  Supports a wide range of audio formats, provides a modern UI with advanced library and playlist management.

grade: devel
confinement: strict

parts:
  one-player:
    source: build/linux/x64/release/bundle
    plugin: dump
    stage-packages:
      - libmpv2
      - libasound2

apps:
  one-player:
    command: one_player
    extensions: [gnome]
    plugs:
      - home
      - network
      - audio-playback
      - opengl
      - wayland
      - x11
      - desktop
      - desktop-legacy
